### ISSUE TITLE
add dye trader 

### ISSUE THREAD

**Issue by ronnor99** [MineInAbyss/Issue-Tracker#102]
### Is your feature request related to a problem?

some dyes are hard to get (from only certain flowers that may be rare or can only be acquired as mob drops which wont be used since they are much more valuable as use for orth coins)

### Describe the solution you'd like.

i would recommend adding all the dyes as as tradable most likely a stack for an orth coin like the wool trade some are farmable and by proxy worth less but it could be better for consistency

### Describe alternatives you've considered.

selling stuff made using dye insted but it would be more confusing for the players and more work for the mods

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

boy told me to place it here i know its not a bug

**Comment by Boy0000** [comment]
[added](https://www.notion.so/mineinabyss/Glass-Master-Gael-060b32c389154bcf933bc857147430e8)
