### ISSUE TITLE
New ore for lower levels -for armor and new recipe ideas

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#103]
### Is your feature request related to a problem?

it helps with players being able to become stronger the further they delve. also could branch into new item ideas.

### Describe the solution you'd like.

it would be a rare custom ore block that spawns in surface deposits that attract mobs to make it harder to get, and it would have a super tiny chance to get while mining.

-spawns in surface deposit chunks that would atract mobs to make it harder to get.

-doesnt spawn too common they would spawn away from each other to keep it rare.

-mega tiny chance to get it while mining.

-we can say its cannon and say its what sovereigns armor is made of or something

-current uses in mind are armor and tools (of course) but also maybe something unique like it can make a placeable item like a custom candle that encourages mob spawn in a radius around it, would need code work so effect doesnt stack and is abused. opposite is also available to where it makes mobs run from the area. like a creeper to a cat.

- could link to a knockback resistance enchant that would have to be crafted.

### Describe alternatives you've considered.

changes to its features are open this is just a idea.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

i can do the art for the blocks and items around it.

**Comment by Kasaichan** [comment]
An ore that attracts mobs already has a use of it's own without being refined into an ingot of sorts, but the risk of obtaining the ore is diminished if you can randomly find it in a manmade quarry or branch mine, where those mobs can't reach you. The candle idea is interesting (reminds me of the [Water Candle from Terraria](https://terraria.fandom.com/wiki/Water_Candle)), but the ore wouldn't be cannon because we're making it up and the ore does not come from the official source.

**Comment by LukyLucas** [comment]
well id love to see something that encourages or blocks mob spawning in the game so that mobs arent constantly outside your door or so that we can actually find mobs bc mobs are so inconsistent. kinda would be nice for getting orth coins

**Comment by LukyLucas** [comment]
kasai should i make a separate github issue for a mob attracting/repelling candle?

**Comment by Kasaichan** [comment]
I'd wait to see who finds this issue, so you don't contradict the Agreement of _I have searched for and ensured there isn't already an open issue regarding this_. I can see this being a feature, but the idea's already here. I've seen @Valienta look through some of these issues recently, so she might have a take on this.

**Comment by Kasaichan** [comment]
In terms of attracting mobs, I've recently found [this relic (function created May 9th, 2021) in the database](https://www.notion.so/mineinabyss/Abyssal-Caller-14d2d1b63e1d449e8b265d7e200b7731) that "summons the closest mob in the area". It has a radius of 50 blocks and has limited uses, but the difference is the target and destination. As of now, it's not released yet, but it seemed related to this suggestion, so I wanted to comment on that.

**Comment by LukyLucas** [comment]
If we add it could I texture it?
