### ISSUE TITLE
Mine in Abyss Wiki

### ISSUE THREAD

**Issue by Kasaichan** [MineInAbyss/Issue-Tracker#104]
### Is your feature request related to a problem?

Helping develop Mine in Abyss for a small amount of time has made me familiar with how it's endless amount of jobs left to do is organized. The work left to do is split into Github and Notion, but the majority of roles go into Notion. At some point, a fandom wiki was created, and I believe it's development was halted.

### Describe the solution you'd like.

Because Notion is already organized with several databases of information, it can be used as a wiki of it's own. It would cancel splitting efforts into a 3rd site, and because Notion is already being actively used, updating the site wouldn't be as repetitive as updating an optional, external wiki. This can also help the designers describe their ideas further and gain an audience to encourage their work. Notion is also available to view without creating a Notion account.

### Describe alternatives you've considered.

There are two complications that could come out of Notion, one being the setup and the other being shared links. While Notion is easily explorable, the information about specific items or mobs are not all complete. The platform is designed to help the development team collaborate, as the space works as a construction zone. The setup process can have additional effort put into clarifying those missing details so there is somewhere to search for answers. On Discord, sharing links to Notion is small enough, but sending these links in Minecraft could obstruct the server's chat. While this alternative requires more effort and participation, making use of the servers emoji system to replace the link with smaller clickable text (at minimum the link to the start of the wiki) can be requested, as well as an easier way to find the Notion page on the website.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Sources:
[Mine in Abyss Github](https://github.com/mineinabyss)
[Mine in Abyss Notion](https://www.notion.so/mineinabyss/Mine-In-Abyss-5d7d8bc07fd04007a459c27ea2019c3f)
[Learned about the fandom existing](https://discord.com/channels/385252444734619680/404816726233186304/861727892064174131)
Temporarily Unavailable [Mine in Abyss Fandom](https://mine-in-abyss.fandom.com/wiki/Mine_In_Abyss_Wiki) and it's [Creature Page](https://mine-in-abyss.fandom.com/wiki/Creatures)

**Comment by VaIienta** [comment]
Think we want to ultimately have a wiki for the Mine In Abyss in game, rather than from an external source and whilst Notion is highly used, its more so for our staff team and than just any other player. Notion will most likely be used for official documentation which will have more development/implementation information opposed to player-needed information and this will become more so with the coming of the design docs but I'd imagine the official wiki will use Quill ultimately.
