### ISSUE TITLE
explosive arrows?

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#110]
### Item Type

Weapon

### Item name

explosive arrow

### Item Info

like how fireworks can be fired from a crossbow but these can be fired from a regular bow and are more concealed than an obvious firework. 

pretty much it explodes on impact and isnt affected by enchants. -wouldn't rlly work with punch ,infinity, might be fine with power but idk.

### Item Model/Texture

none but can design.

### Obtainability

crafting

### Additional info

would be crafted with a arrow (not with potion or spectral arrows) and gunpowder (the stuff that one mob drops), paper, and a piece of iron, to light it obvs.

[O][P][_]
[P][G][P]
[_][P][A]

O-iron
G-gunpowder
P-paper
A-arrow

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the relic I'm suggesting isn't already on the server.

**Comment by LukyLucas** [comment]
lol my crafting grid looks funni

**Comment by LukyLucas** [comment]
looked at this again and thought it could be different on crafting,

[O][R][O]
[G][S][G]
[P][F][P]
O-iron
R-pressure plate
S-stick
F-feather
P-paper
G-gunpowder

**Comment by LukyLucas** [comment]
im going to make the texture for it and submit it here so someone can give me thoughts on it. im muted after all.

**Comment by LukyLucas** [comment]
sooooooooooo heres something for a texture.... i honestly thing the explosive top isnt bad but the body and feather are kinda terrible if u ask me... wanted it to look like a cyatoria feather but failed there...
![explosive arrow](https://user-images.githubusercontent.com/102488303/163278381-a9bc6be0-ee9e-423d-82b4-1d5549880fbb.png)

**Comment by LukyLucas** [comment]
might be hard to view its 16px by 16px

**Comment by CptA4** [comment]
My brother in christ, please no more

**Comment by LukyLucas** [comment]
Look in just trying my best to contribute

**Comment by LukyLucas** [comment]
They CAN reject it if they don't like it

**Comment by Boy0000** [comment]
There are already arrows in the pack. Specifically taken and modelled from examples from the show.

Just not used atm. The feature itself is also already planned so closing this

**Comment by c-sig** [comment]
my brother in christ, these are just fireworks

**Comment by LukyLucas** [comment]
These would be used in bows and are more expensive. Also they are more concealed so if you see someone in a pvp layer you can bow them down without them knowing where you are.

**Comment by LukyLucas** [comment]
Fireworks have all the effects and sound which may draw in third parties or give away your position. Fireworks are also timed so they can only go so far

**Comment by c-sig** [comment]
my brother in christ, minimaps exist. any person seeking pvp would have it and gunning down noobs with expensive arrows is not cost effective

**Comment by LukyLucas** [comment]
Not everyone goes out thier way for a minimap and what if it's Real pvp against a equal opponent

**Comment by c-sig** [comment]
my brother in christ, have you not experienced pvp before

**Comment by LukyLucas** [comment]
Next time I see a random guy in L5 I would totally load these up

**Comment by LukyLucas** [comment]
Bro I spent all my time on hypixel and 2b2t

**Comment by c-sig** [comment]
my brother in christ, yes but we are talking about this server no 2b or hypixel

**Comment by LukyLucas** [comment]
Yes btw most of my fights take running away from ppl with better armor

**Comment by LukyLucas** [comment]
But with these I would bow them down without showing my position or getting close

**Comment by LukyLucas** [comment]
If they become meta ppl would actually use the useless blast protection

**Comment by c-sig** [comment]
my brother in christ, there is no pvp meta in this server. its always a battle of attrition because keepinv isnt off
