### ISSUE TITLE
HiddenOre Calcite

### ISSUE THREAD

**Issue by trailsideNils** [MineInAbyss/Issue-Tracker#111]
### Expected behavior

Expected Calcite to spawn ores with at least close to the same chance as other blocks in the area.

### Observed/Actual behavior

0 spawns over the course of 200 Calcite mined.
Given L3 ore spawn probabilities, the odds of any spawn occurring is 5.99%.
The odds of at least one spawn occurring over the course of 200 blocks is 99.99957%...
Meaning that the chances of consecutive no-spawns for 200 blocks is 0.00043%. I'd expect to see a diamond before this happens.
Probabilities and all that, but something's off. Calcite is noticeably doing nothing.

### Steps/models to reproduce

Break some calcite I guess.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have made a detailed description of the bug so that it can be reproduced.

**Comment by Boy0000** [comment]
Calcite is deliberately missing from list of blocks that can spawn ores

**Comment by trailsideNils** [comment]
Are there any other minerals in the world that are like that? Feels like exceptions to the rule should be made plain so no one scratches their head for hours wondering what's going on like I did.

**Comment by Boy0000** [comment]
You can read over what blocks can trigger Ore spawns [here](https://github.com/MineInAbyss/server-config/blob/master/servers/survival/plugins/HiddenOre/config.yml)
