### ISSUE TITLE
Quiver

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#113]
### Item Type

Equipment

### Item name

Quiver

### Item Info

I Know it was in Minecraft a long time ago, but we could probably add quivers. it's fine if you just don't want to work on it. I can't rlly do any coding yet so someone else would have to code this in unless we steal the code for the quiver that was in earlier versions.

### Item Model/Texture

i can make one but theres already a existing texture.

### Obtainability

crafting

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the relic I'm suggesting isn't already on the server.

**Comment by Boy0000** [comment]
Cant really just "steal their code" when the code your suggesting has been gone for years and is from a closed source. Also whats the point of a quiver? A slot can hold 64 arrows and Infinity is an enchantment
