### ISSUE TITLE
Dungeons

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#115]
### Is your feature request related to a problem?

So I saw on some relic pages that they were obtainable in "dungeons" and I came up with a dungeon concept that could be added. 

### Describe the solution you'd like.

They would have a built preset added to several spots in each layer, some hidden some not.
They would contain rooms of mobs and loot and a final room with a "boss" like a stronger version of the mobs in that layer or something.
After being looted the dungeon would close for a set amount of time and reset. The blocks in the dungeon would be unbreakable except for hidden room entrances and the loot crates would have a random set of loot like relics and materials. 

### Describe alternatives you've considered.

Each dungeon could have a theme based on what layer it's in or the mobs/challenges within. Because there's multiple in a layer the farther down the more challenging they'll be. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Am willing to do dungeon design or discussing further on the concept. If needed I could make a base idea for a dungeon build in a creative world and submit it.

**Comment by LukyLucas** [comment]
Forgot to say they could have a completion reward at the end like a banner as proof of completion. They would obtain one every time they beat it and in the item description it would have thier name and attempt number.

**Comment by Boy0000** [comment]
This is already planned to happen someday
