### ISSUE TITLE
invisible birds

### ISSUE THREAD

**Issue by somking08** [MineInAbyss/Issue-Tracker#117]
### Expected behavior

I expected to be able to consistently see the hammer beaks, corpse weepers, and cytorya (I dont remember the exact name)

### Observed/Actual behavior

Half the time said birds where invisible, and would make doing anything hard because you can fight something you cant see.

### Steps/models to reproduce

step one.Go into the abyss
step two. observe 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have made a detailed description of the bug so that it can be reproduced.

**Comment by Boy0000** [comment]
Its a known issue yeah and one that has been there for a good while.
It is being fixed but its taking some time 👍
