### ISSUE TITLE
crafting without needing a table

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#119]
### Relicname

crafting panel

### Relic Location

not sure where to put it.

### Relic Info

literally just something to keep in your inventory and when you hold it and right click it brings up a crafting grid.
it can have a durability that goes down with every use.
like 100 uses or something.

### Relic Model/Texture

i havent made one

### Related recipe ideas

none

### Additional info

another idea i had was adding backpack upgrades like a fluid canister, crafting, or smelting. makes backpacks even more essential ig.

fluid canister- holds three buckets of lave or water. never both.
crafting/smelting- literally just one of these two in the backpack.

also had the thought of a item that holds more than a bucket of lava or water

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the relic I'm suggesting isn't already on the server.

**Comment by Boy0000** [comment]
This would be implementing a feature to replace 4 planks of wood.
From a development perspective the time spent making this would be a waste.

also split others into actual suggestions as I will close this one
