### ISSUE TITLE
Seasons

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#120]
### Is your feature request related to a problem?

This would probably take quite a bit of work but the basic idea is different seasons in the abyss but a bit deeper. They wouldn't effect the entirety of the abyss but have individual effects in each layer. This could be like a snow season in layer 1 which would cause snow and ice to form. This would work because alot of layer 1 is slopes that ppl just mine or place blocks down. I could see someone slipping on ice on thier way down (lol). Another concept is a spring season which is related to breeding so the effects would be a increase in mobs and there would be mobs with certain effects like strength (because they gotta fight for mates). I think this could add some more complexity to the abyss for the better.

### Describe the solution you'd like.

I totally see how much work this might be so its fine for a rejection however just simulate in your head how this could change the abyss and how it could keep things from always being the same each time you descend. 

### Describe alternatives you've considered.

If be glad if anyone who read this would ask questions and build on the idea in the comments. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

I listed two season concepts but there should be more ofc.

**Comment by LukyLucas** [comment]
Was thinking this could come with a downloadable pack that works with optifine and just expands on visuals specifically for the abyss and would work in each layer not a one size fits all. Unless we already have that, not sure.

**Comment by Kasaichan** [comment]
Similar Feature that's been buried here and left alone for years to come: [https://www.notion.so/Difficulty-Increase-At-Night-edca0903eeb1498ca867b83fb45dedbd](https://www.notion.so/Difficulty-Increase-At-Night-edca0903eeb1498ca867b83fb45dedbd). Pretty much a difficulty spike at expectable times, like the mobs becoming more fierce. To quote in the wrong context from Madi for why this will take a while to add, [_"Mobzy is basically Offz's ugly child that nobody wants to touch except Offz :kekw:  but yeah all the devs are working on other things rn"_](https://discord.com/channels/385252444734619680/876966112779173958/967113332890947644)
Slippery Concept does make me think about the strong winds in the inverted forest, the bridging / rope (also soon:tm:), and the slippery factor turning the controls into a rage game. Beyond that, I have considered creating outfits for NPCs for future events (It's been 4 months... ) arranged towards general holidays, but I haven't confirmed if that could happen.

**Comment by Naatchi** [comment]
comment above closes this issue (i think?)
