### ISSUE TITLE
Apex Mobs

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#122]
### Mob name

Apex Mobs

### Spawn Locations

.

### Mob-type

Hostile

### Mob Info

ok so these would be the more dangerous mobs in lower layers.
the same type of apex mobs wouldn't spawn anywhere near each other but its fine for different apex mob types to be near each other, however they are enemies. they would have impressive fight scenes when they find each other and afterwards they would run away from each other.

basically bosses that roam l5 and fight each other. they would have high health but only slightly stronger than average damage (some mobs already shred players in enchanted armor) for players to bring one down they would probably need teamates or just have a good strategy. for ai it would be relatively simple however on certain hp percentages they would run to another location. not too far away but enough to where players cant use a strategy like trapping it on a corner till death. they could probably have boss bars for thier health.

yes this idea is inspired by monster hunter but i think its a good idea. im happy for anyone to ask questions on the idea to clean it up.

### Mob Model/Texture

havent made any concepts yet but i imagine one or two sea apexs for l5 then a few to stick to land.

### Related mobdrop ideas

they can have thier own mob drops bc i imagine there would be three to four apex types in a layer however im thinking they have a expanded loot pool full of randomized armor and tool drops as if they had eaten delvers. maybe even some relics.

### Additional info

the main idea is stronger mobs that dont spawn near each other but will fight each other upon contact. (players would love to watch these fights and i can imagine players leading these guys too each other to fight them weakened.)
basically roaming bosses 

not everyone will envision this the same way upon reading so please ask questions if you need too.

apexs would be a great way to add the larger mob ideas that might seem to powerful due to the fact that these apex mobs would be rarer than normal mobs.

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the mob I'm suggesting isn't already on the server.

**Comment by Kasaichan** [comment]
[(This became a discussion in #suggestions you were a part of, documentation here.)](https://discord.com/channels/385252444734619680/876966112779173958/968213021044396114)
