### ISSUE TITLE
Tonbufo

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#124]
### Mob name

Tonbufo

### Spawn Locations

Layer 3/4 maybe would be good in l2. 

### Mob-type

Flying

### Mob Info

On its own its relatively weak and runs from players, however when a target entity is detected it will move to it and once it does it will be moved on top of it by riding, same as those mob tower things. It is not targeted by other entities, if that's possible. Once on the targeted mob it applies speed 1 and either resistance or health boost. 

### Mob Model/Texture

Haven't made one yet however now that I can make models I'll supply one.

Appearance looks like a hornet with dragon fly eyes and wings plus it'll have a model for when it's attached where a needle in the back sticks down into the entity it's attached too. 

### Related mobdrop ideas

Tonbufo adrenaline, doesn't stack and when used it buffs the player with speed 1 and strength 1. It will have a cooldown of 60 seconds and the effect lasts for 15 seconds. (I don't know if these are good values, might be adjusted.)

### Additional info

If mod thinks it should be different pls let me know and I'll adjust appearance. 

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the mob I'm suggesting isn't already on the server.

**Comment by LukyLucas** [comment]
> 
[Tonbufo.bbmodel.txt](https://github.com/MineInAbyss/Issue-Tracker/files/8593123/Tonbufo.bbmodel.txt)

**Comment by Boy0000** [comment]
why is this a txt file

**Comment by LukyLucas** [comment]
Idk I tried to upload it

**Comment by Kasaichan** [comment]
Corrected format for the mob's art:
[Tonbufo.zip](https://github.com/MineInAbyss/Issue-Tracker/files/8594463/Tonbufo.zip)
Keep it as a .bbmodel for mobs or export as a .json for blocks, but share the files you used in a .zip.
![image](https://user-images.githubusercontent.com/102488431/166062569-b6927711-9758-4709-ad1e-0b5e16a68eb4.png)


 Picking on the design of the Tonbufo:
 > A Metroid that gives buffs upon applying itself on to you. Why would it rely on creatures to support them? The idea of giving minor buffs to the player is similar to the [Pendant Lure of the Deep](https://www.notion.so/mineinabyss/Pendant-Lure-of-the-Deep-e9b2f873767e47dcacb5d5b7ada2e3a0), [Slime Gland](https://www.notion.so/mineinabyss/Slime-Gland-3bd65145fbb34fee9233182e67e924cd), and [Centipede Heart Pin](https://www.notion.so/mineinabyss/Centipede-Heart-Pin-a556411a1d15410585f221eea2a4fb39)s. In terms of mobs being allies, the closest mob that brings support is the [Beniguma](https://www.notion.so/mineinabyss/Beniguma-b30bc511b2f141e8bffb49903e2212f1), a layer 1 exclusive creature that only helps you find food because you fed them. Layer 1 is the safest of layers and only having one support mob is good enough.
 
 > Appearance perfectly describes the [Kagi Tachikiri](https://www.notion.so/mineinabyss/Kagi-Tachikiri-b49a65314dc841acbb108213d016b25b), and the [Oni Tachi-Kiri](https://www.notion.so/mineinabyss/Oni-Tachi-Kiri-85b0ea1c34e74adf939036b9938a87b1), which in lore was spotted at the surface at one point but is expected to be found in the fifth layer. To relate to the Tonbufo, the appearance has already been used in another mob.
 
 > Mobdrop is a free potion. For it's danger level, the obtainability of it is not earned. Even minibosses such as [Steve](https://www.notion.so/mineinabyss/Steve-d4c6c4808c314e04950fd3c2aae87ca0) don't give you something immediately useful. They're crafting recipes that [cost a ton in shops](https://mineinabyss.notion.site/Odroy-The-Apothecary-c231f8d309634726845812bd1e6bc7fe).
 
 > If you have to ask to change everything in the additional info, it shows you aren't sure about this suggestion. Work it out with me or those in suggestions. There's not much I can do to recover this mob so it would be better to start with a new idea.

**Comment by LukyLucas** [comment]
its not a ally it buffs other mobs

**Comment by LukyLucas** [comment]
it doesnt attach to players

**Comment by LukyLucas** [comment]
also i just tried one it can change
