### ISSUE TITLE
goblet mob

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#125]
### Mob name

Raifuru Ebi

### Spawn Locations

layer 4 in water.

### Mob-type

Hostile

### Mob Info

one attack with 6 second charging intervals, fires two visible rapid succession beams with about the damage of a harming arrow in each shot. if player holds a shield the player is knocked back about 4 blocks. the range is about 10 blocks but should be dodgeable. when not firing it moves backwards away from player to try and maintain a distance of 5 blocks. if the shrimp fires and player is within 3 blocks it lights player on fire, doesnt quite help if player is in water although being in water slows you down so it is quite effective at making the player back away for a second.

### Mob Model/Texture

![gshstrtrstsr](https://user-images.githubusercontent.com/102488303/166316704-cd6a99cd-81ba-4571-a60d-e91df7b7330a.png)
2.5 H, 3 L, 2 W. if faputa does make the better concept art ill add it here.

Randall's pistol shrimp is the original shrimp not saying owned by Randall, its CALLED Randall's pistol shrimp.

### Related mobdrop ideas

Tasty claw meat- just food, possible soup recipe called shrimp scampi.
kaleidoscopic eye- like the vanilla telescope but fractal's the view like a kaleidoscope. its the cut off eye of the mob lol.
Ebi legs- sticks. yes sticks. regular old sticks. needed a filler mob drop and the legs look like stick legs soooooo

### Additional info

method to beat-
stay close but not too close and repeat dodging and attacking. right before it fires is a good time to avoid and eat if health is low. attacking right after and repeating is a easy way to kill them. (based off the described behavior its how i would fight them.)

heres a kaleidoscope image
![image](https://user-images.githubusercontent.com/102488303/166317460-8ebef827-8029-482f-b2a1-366a72f0ffe0.png)
kasai liked the mob so i hope it has a good chance

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the mob I'm suggesting isn't already on the server.

**Comment by VaIienta** [comment]
Wooo... Another hostile mob. Ok there is a lot of illogical ideas here to be frank. 

> 2.5 H, 3 L, 2 W

Not too sure what this related to in size, metres? centimetres? This creature looks absolutely tiny (assuming you looked from google too... Randall's Pistol Shrimp is tiny) and would have to be to be an aquatic mob living in a goblet... So why would it be hostile in a sense where it attacks violently? Small creatures don't do this in real life... they are either silent deadly killers or work tactfully in a swarm using something beyond pew pew lazer beams to kill their enemy.

> if the shrimp fires and player is within 3 blocks it lights player on fire, doesnt quite help if player is in water although being in water slows you down

Ok so fire... from an aquatic creature? And this just seems like your trying to make some tiny creature more and more overly hostile in an unconcise way?

Also if something is so small how would it ever create the force to knock a player back 4 blocks, the player would go flying before it ever saw the thing.

> Ebi legs- sticks. yes sticks. regular old sticks. needed a filler mob drop and the legs look like stick legs soooooo

If it's just a filler there is no point in having it.

I think you would be better to think of an L5 aquatic creature, we have like nothing there. L4 has mostly water in goblets and that already has Orbies, Rohanas and Kazuraikas. 

You really need to rework this mob, might be better L5 and non-hostile. Don't give this a 2 minute think either probably reconsider. A shrimp isn't a bad starting spot but make it abyss-y and make it   **_l o g i c a l_**.

**Comment by LukyLucas** [comment]
So the size was in 16 by 16 blocks. Fire is a nod to the fact that pistol shrimps create a Shockwave apparently as hot as the sun.

**Comment by LukyLucas** [comment]
Definetly glad for your thoughts though! ig the way I put things in weren't clear enough on size and I was thinking that the goblets just doesn't have enough life to them compared to what we have for the rest of the abyss. I also think I should expand on the non hostile environment mobs since they would supply to adventure cooking and overall make the environment less dead feeling.

**Comment by LukyLucas** [comment]
Also fire does seem unrealistic but it's a good way to keep ppl from cheesing it by staying out the water. It says hostile but I think it could be neutral as in it kinda chills till it has to defend. After all it's not trying to get close to the player.

**Comment by LukyLucas** [comment]
Also is the kaleidoscope thing with the eye drop possible?
