### ISSUE TITLE
Stuck in pvp zone

### ISSUE THREAD

**Issue by Marvinutil** [MineInAbyss/Issue-Tracker#143]
### Expected behavior

Im in pvp zone w/ a friend we can't get out, the server is kicking us 
like, we cant even load the resource pack

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/110504623/182495477-0be44615-1b7f-4a8f-8477-62a320baee20.png)

### Steps/models to reproduce

cant even take a screenshot of my coords im instantly kicked

### Other

sorry i'd have to lie for the second agreement titled: 
"I have made a detailed description of the bug so that it can be reproduced."

Look discord #reportbug if the screen does not load on github

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have made a detailed description of the bug so that it can be reproduced.

**Comment by Boy0000** [comment]
Update to 1.19.x and see if that helps. Error usually happens on 1.18.2 which is mostly not supported rn
