### ISSUE TITLE
gamemode change when teleporting between worlds

### ISSUE THREAD

**Issue by Moonave** [MineInAbyss/Issue-Tracker#15]
can you make the gamemode stay the same when teleporting between worlds only for staff ty

**Comment by Derongan** [comment]
Could you clarify? I'm assuming you mean on build. What is the exact issue?

**Comment by Moonave** [comment]
for example tping between creative world and adventure world causes u to change gamemode automatically to gm 0

**Comment by Derongan** [comment]
Oh to let staff stay in creative? This is teleporting using mvtp correct?

**Comment by Moonave** [comment]
Yep

**Comment by Derongan** [comment]
This should now be fixed
