### ISSUE TITLE
Figure out a way to solve the darkness in L2S1

### ISSUE THREAD

**Issue by MilitaryPrincess** [MineInAbyss/Issue-Tracker#18]
Large amounts of L2S1 suffer from being super dark since they're in the shadow of the cliff at the top, making them unnavigable for people with low brightness/gamma, which ends up leading to huge contrast with the section below where the cliff above is no longer rendered.

Not a super urgent thing but if there's a quick fix then that'd be cool

**Comment by Derongan** [comment]
Hrm. So we can either brighten one or darken the other. Permanent twilight might fix some of this in a simple way. 

Do you think all dark or all light is better?

**Comment by LoneReborn** [comment]
Layer two should be mostly light so lighten one area we could do what's done in other layers with sea lanterns but they fit in on the lower layers not higher levels.
