### ISSUE TITLE
Add an arena for combat related events.

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/Issue-Tracker#2]
It would be ideal to have an arena somewhere in the map to hold combat events. The arena would ideally be suited for FFA or Team fights.

This arena should provide cover and should have high and low regions. 
Ideally it would be fit into the abyss in some way that remains thematic. It should be accessible from the city (a Ido Front arena would be cool, but it should be easily accessible without unrealistic magical teleports).

Some suggestions for location:

1. An island some ways away from the dock.
2. Carved into the mountain. This way it won't affect the visual of orth. We lose natural lighting though which is a shame.
3. Repurpose some other large building. This would be interesting but in my opinion even the guild towers are a bit too small for a good arena.

Thoughts?

**Comment by Miirpat-Gaalsien** [comment]
I'd say the (or at least a) arena has to have the curse significantly to reflect the combat experience of having the highground.

**Comment by LoneReborn** [comment]
Best idea is an island off away from the docks. We need most of the space in Orth unless we build it underground.

**Comment by Waterbeacon** [comment]
@LoneReborn battles or testing grounds seem scummy, and with the society in MIA I think the best place would instead be the slums or the underground slums if that becomes a thing

**Comment by LoneReborn** [comment]
@Waterbeacon If I can fix fps issues in slums underground slums is a large possibility. We already have a prototype area underneath so that can be expanded if needed for the time being I need to test fixing the lag.
 May need to task mup to help build the caverns needed

**Comment by Derongan** [comment]
I honestly think island might be better just due to free sun as a light source.

**Comment by 0ffz** [comment]
We could have people go in a boat and trigger a relative teleport (similar to deeperworld), which could be a pretty nice transport method. Also, change the skybox to have a render of the abyss as seen from a far, it'd make it feel like it's still part of the same world and is probably the easiest way to do this. We can always have multiple arenas, in which case I think the slums would be great, or really just anywhere outside Orth.
