### ISSUE TITLE
Disconnection over the repeated usage of climbing plugin

### ISSUE THREAD

**Issue by TurdNugget** [MineInAbyss/Issue-Tracker#25]
Whenever I start using the climbing tool repedately for quick and efficent diving i get a disconnect with the reason "moving unexpectedly"
Need to do further research on the subject
One of the "warnings" seem to be "glitch falling" wich can be accomplished by using and disabling the climb tool midway trough a fall; resulting in a constantly stopping and starting (almost like shaking) fall and the apropriate amount of fall damage according to the players position at the moment of the cancelling of the climbing tool.

**Comment by LordOfTheDeer** [comment]
said glitch falling can happen anywhere and is cause by falling for an extended period of time, it happened when i was using the fast fall.

**Comment by 0ffz** [comment]
Unsurprising that the server isn't used to it, maybe I could look at ways to tell the server to ignore any flying related kicks while you're climbing.

As for the second part, not 100% sure what you mean, but the climbing plugin does give fall damage when beginning to climb after you've fallen enough. It's to prevent someone from grabbing onto a ledge last second and surviving. Could possibly just be a bug with that system. 

I'll revamp the plugin eventually, maybe the second problem will fix itself.
