### ISSUE TITLE
Resource pack glitch

### ISSUE THREAD

**Issue by RRainJE** [MineInAbyss/Issue-Tracker#27]
If you turn on the resource pack in another world, it crashes the game and keeps crashing it when you try to reload it, so you have to manually deleted from the minecraft files. It was pretty annoying to do, can you guys please fix it?

**Comment by 0ffz** [comment]
Do you have optifine? If you don't I might know the problem and how to fix it

**Comment by RRainJE** [comment]
I don't think I used optifine

**Comment by 0ffz** [comment]
I can't seem to reproduce what you've described. do you have server resourcepacks enabled or have you downloaded it manually? 

You can turn on server resourcepacks by doing the following: 
![enablepack](https://user-images.githubusercontent.com/16233018/63546764-8c857200-c4f8-11e9-823a-095cd1facbe5.gif)
