### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Moonave** [MineInAbyss/Issue-Tracker#28]
i feel like something like this has been mentioned already but like maybe we can have a leaderboard where like the amount of relics youve collected give you a certain amount of points, (the more rare, the more points) and the more points you have the higher in the leaderboard/heirachy you are in.

**Comment by 0ffz** [comment]
We'll have something similar in the planned gamemode, with [levels and xp](https://github.com/MineInAbyss/MineInAbyss/issues/23). Stay tuned :p
