### ISSUE TITLE
kicked whilst connecting to build

### ISSUE THREAD

**Issue by xalcolm1** [MineInAbyss/Issue-Tracker#30]
this error displays when I try to connect to the server, It is followed by the message " Outdated server! I'm still on 1.13.2"

**Comment by Derongan** [comment]
Are you using 1.14? The server is running 1.13

**Comment by xalcolm1** [comment]
I figured out that that was the issue, but how do I change the game version?

**Comment by Derongan** [comment]
You should be able to follow these instructions https://help.mojang.com/customer/portal/articles/1475923-changing-game-versions

**Comment by xalcolm1** [comment]
thank you!
