### ISSUE TITLE
Layer 3 is too difficult to traverse

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Issue-Tracker#31]
It's hard to make out where you are within caves, but even worse, there are no reasonable paths to get to the caves in the first place. Additionally, the caves don't properly connect between sections, making it possible to get completely stuck.

It may help to allow scaling the walls of the layer without entering caves by creating more ledges. Think of some parkour that works well with the climbing system.

**Comment by Mayonnaise5324** [comment]
The only option to make it easier is to add more tunnels for the Neritans. They should be smaller tunnels that go usually from one space higher to one space lower. It makes going down much more fun, as well as easier. Don't need to add giant tunnels that get people lost.
