### ISSUE TITLE
Bees do not work in layer 4/5

### ISSUE THREAD

**Issue by sawe871** [MineInAbyss/Issue-Tracker#38]
Bees do not work in layer 4 and 5.  I found a bit of code that should be able to solve it.

https://www.spigotmc.org/threads/make-bees-active-at-night.408625/

**Comment by Paul1365972** [comment]
Hacky solution [Paul1365972/NocturnalBees](https://github.com/Paul1365972/NocturnalBees).
Alternatively one would have to edit server source code

**Comment by 0ffz** [comment]
@Paul1365972 Would it be possible to listen to some event for the bees entering at night and set cannotEnterHiveTicks when they try to enter at night?

**Comment by Paul1365972** [comment]
Well yes it is possible, but then either the bees will then never enter the hive at night anymore or they would be stuck in there until day comes, as the day check takes priority.

**Comment by Boy0000** [comment]
seems solved :)
