### ISSUE TITLE
Setsuna

### ISSUE THREAD

**Issue by MilitaryPrincess** [MineInAbyss/Issue-Tracker#4]
She's super cool and I want her
Reasons:
She can kick and ban, and logs the reasons for doing so and sends the user a message on why. 
She can also auto-kick spammers 
She can add warnings to people that persist even after they've left
She's not made by some random, I know the guy who made her
She can issue warnings to people that send messages to them and also add to their account
You can index members through it to see who has kicks and bans
She's customizable to the specific server so she works per server
I love her she's cool

**Comment by Derongan** [comment]
Could you provide a link to the Bot?

**Comment by MilitaryPrincess** [comment]
https://github.com/r-anime/ZeroTsu

**Comment by Derongan** [comment]
@MilitaryPrincess could you justify this over 42?

**Comment by MilitaryPrincess** [comment]
But I already did :.(

**Comment by MilitaryPrincess** [comment]
oops

**Comment by 0ffz** [comment]
Now using dynobot for this
