### ISSUE TITLE
Water bug all layers (i think)

### ISSUE THREAD

**Issue by Zekelle** [MineInAbyss/Issue-Tracker#44]
**Describe the bug**
the water is kinda weird in layer 3 4 or 5 never tried the layer 1 and 2 tho so im not sure if it happens in all layer so the bug is all about the water, something in it that ur being sucked up. its so hard to go in the surface of the water cuz as i said its like ur being suck up.

**To Reproduce**
1. Go to '...' layer 3, 4 and 5

**Comment by 0ffz** [comment]
This is an intended feature but needs to be changed as it currently doesn't give enough feedback as to what's happening.

Just made an issue here: https://github.com/CultOfClang/BoneHurtingJuice/issues/19

**Comment by Boy0000** [comment]
fixed
