### ISSUE TITLE
HiddenOre does not drop ores with silk touch

### ISSUE THREAD

**Issue by Seedl1ng** [MineInAbyss/Issue-Tracker#48]
**Describe the bug**
when mining with a silk pickaxe no ores spawn 

**To Reproduce**
1. Go to an area with stone
2. mine 
3. Use a silk pickaxe

**Expected behavior**
i expected for ores to spawn but i mined like 200 blocks and nothing but i used a normal pick and shit spawned normally 

**Screenshots**
dont have one

**Additional context**
only happens with silk picks prob would happen with all silk tools

**Comment by pixelfac** [comment]
Is this still a bug? I looked at the HiddenOre config and there's an 'ignore_silktouch' property there so I wasn't sure if this had been addressed yet or not

**Comment by 0ffz** [comment]
@Boy0000 thoughts?

**Comment by Boy0000** [comment]
Yeah its weird that it doesn't atleast spawn the ores. Have it behave like normal minecraft, I don't see why not

**Comment by pixelfac** [comment]
I'd like to work on that, but I can't find the HIddenOre repo.

**Comment by Boy0000** [comment]
Yeah it's not our plugin, but setting it to true in config fixes it. I'll just do that

**Comment by Boy0000** [comment]
Can't close the issue @0ffz but it is fixed now
