### ISSUE TITLE
Update discord FAQ to include reference to this tracker

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/Issue-Tracker#5]
In order to speed up adoption, it would be valuable to have some info on how to use this inside the FAQ in #information

**Comment by MilitaryPrincess** [comment]
Can we have a 'Use a site that doesn't have the notification functionality of a dying mute goose' issue brought up please?

**Comment by Derongan** [comment]
@MilitaryPrincess it sends me emails every time an issue is updated.

**Comment by Derongan** [comment]
Ive noticed you updated- but the link should be to https://github.com/MineInAbyss/Issue-Tracker not to https://github.com/MineInAbyss/ can you update it? After that feel free to close this issue
