### ISSUE TITLE
Kidnap NPCs with Minecarts

### ISSUE THREAD

**Issue by robert144144144** [MineInAbyss/Issue-Tracker#54]
**Describe the bug**
You can kidnap the NPCs (Regs and Rikos) with Minecarts.

**To Reproduce**
Place minecart track underneath any NPC, push empty minecart as the NPC will go in, break Minecart then NPC moves.

**Expected behavior**
I dunno

**Screenshots**
No

**Additional context**
Is this intentional? I don't see why someone would ever want to do this. I was just bored and playing around with all the neat toys. People don't know about this, but when they find out they could totally kidnap the NPCs... If someone wanted to be a true griefer they would throw Nanachi into the void.

**Comment by 0ffz** [comment]
Ooooh, didn't think of that, it should be pretty easy to fix soon:tm:
