### ISSUE TITLE
Inbyos near the Great Fault [bug]

### ISSUE THREAD

**Issue by Executie-UwU** [MineInAbyss/Issue-Tracker#6]
While a friend and I were about to transition into the great fault at the end of the second layer, we were attacked by Inbyos that were invisible, likely due to some of their models being frozen in place elsewhere. There was no way to fight back and we were both eventually killed, any ideas why this happened?

**Comment by 0ffz** [comment]
I'm adding options for spawns specific to sections (so they only spawn in the inverted forest), and I'll make the new plugin remove all the old custom mobs to avoid invisible mobs. Will most likely do this next week.

**Comment by Derongan** [comment]
Would a /killall fix it?

**Comment by 0ffz** [comment]
The new plugin now removes old custom entities
