### ISSUE TITLE
flying and dangerous mobs spawnrates

### ISSUE THREAD

**Issue by entity14** [MineInAbyss/Issue-Tracker#60]
**Describe the problem**
i believe the spawnrates should be higher, I rarely see them

just my opinion

**Comment by c-sig** [comment]
already being worked on at https://github.com/MineInAbyss/server-config/issues/29

**Comment by Boy0000** [comment]
@entity14 sure, they should spawn more, but its buggy. You can also just uknow, make a suggestion for what it should be instead of just opening an issue.
