### ISSUE TITLE
Current Creature list and designation

### ISSUE THREAD

**Issue by Waterbeacon** [MineInAbyss/Issue-Tracker#7]
Current Creature List and Desegnation:

Layer 1:
Silkfang - Agressive  
Hammer beak - NEUTRAL 
Fuwagi - Passive, could possibly be a Pet
Lizard - PASSIVE
Moth - Soul Eating. No its PASSIVE 
OC Chikomi - Passive

Layer 2:
Inbyo - Agressive 
Hammer beak - neutral
OC Spearbeak- agressive (Waterbeacon)
Corpseweeper - Agressive
OC 2x Unnamed birds of paradise - passive (Waterbeacon)
Rohana - Passive

Layer 3:
Neretantan - Neutral, Tasty
Crimson splitjaw - Agressive
Madokajack - agressive
OC Squidfly - passive (Waterbeacon)

Layer 4:
Orbed peircer - agressive
Squid - passive
Hammer beak - neutral
Shroombears - Passive
OC Paradise birds?  (Waterbeacon)
OC Crawler - Agressive (Waterbeacon)
OC Strider - Passive (Waterbeacon)

**Comment by Derongan** [comment]
@Waterbeacon is this intended to be for modeling or for implementing them on the appropriate levels?

**Comment by Waterbeacon** [comment]
@Derongan this is just a current list of Creatures and their layers, completed creatures have their files uploaded on the Assets drive and are ready for implementation

**Comment by 0ffz** [comment]
Thanks for the list @Waterbeacon, if you can, put up some behaviors, item drops and how they should spawn (e.x. on cliffs, in groups, in water, etc...) for each creature. Pathfinders are powerful enough to do custom AI (I just gotta learn them a little more). We should probably have a spreadsheet on the Google Drive for this.

**Comment by Waterbeacon** [comment]
@0ffz I will be putting up a more comprehensive list up on the Google drive, I just didn't want a massive document sitting up here

**Comment by 0ffz** [comment]
Closing old issues. For future reference, a list of the mobs can be found [here](https://docs.google.com/spreadsheets/d/1sv_D_yci_trhOyjUe2mLlqhtI38cNVQrXub_T0MPAKY/edit#gid=0)
