### ISSUE TITLE
hamashirama raw slurp

### ISSUE THREAD

**Issue by CptA4** [MineInAbyss/Issue-Tracker#79]
### Type

Shapeless

### Ingredients for the recipe

H: Raw hamashirama

### Result

Hamashirama Slime

### Crafting table recipe shape

```bash
|   |
| H |
|   |
```

### Additional info

One Hamashirama would make 4 Hamashirama Slime and the each Slime will restore either 0.5 hunger or 1 hunger. I would say 0.5 but then there would be no point in crafting it since Raw Hamashirama gives 2 hunger so _(1 food x 2 hunger = 4 food x 0.5 hunger)_ there would be no gain but maybe the slime can give 0.5 hunger but also temporary saturation or some other small benefit.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the recipe I'm requesting isn't already in the server.

**Comment by Boy0000** [comment]
Hamashirama cooked is already "slime". Got no way to apply custom saturation and hunger yet, so rn it is all based on vanilla.

Eventually it will probably be a thing tho
