### ISSUE TITLE
Patreon Feature: Armour Stand Arms

### ISSUE THREAD

**Issue by khaazz** [MineInAbyss/Issue-Tracker#83]
### Is your feature request related to a problem?

I would like the ability to add arms to armour stands so they can hold things like the patreon shields and bows.

### Describe the solution you'd like.

A vanilla mc command could be added to be accessible to patrons (possibly of the second tier) to be able to add arms to armour stands.

/data merge entity @e[type=armor_stand,sort=nearest,limit=1] {ShowArms:1}

This adds arms to the nearest armour stand. This specific command line could possibly be made into a simpler command through a plugin of some sort so that player cannot change any of the arguments within it.

### Describe alternatives you've considered.

Alternatively, the same thing, but not as a patron exclusive command.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
Currently the plugin is abit wacky for it and wont be adding many new perks for a while to patreon to focus elsewhere.
