### ISSUE TITLE
Shopkeepers

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Issue-Tracker#9]
A system for trading to liven up Orth.

We could definitely use an existing plugin, we could also customize it to our needs, but regular villagers wouldn't work. 

The plugin should be able to let players trade items for items, or potentially to buy and sell items with currency (we'd need to decide whether currency would be a physical item, like coins, or just a stored value). It should also be very simple to setup new merchants, and later on maybe even allow for changing prices over time for currency (i.e. some items are more wanted during certain "seasons", or slightly different prices each day)

Later on, I'd also like to see some other systems for upgrading items. Some sort of blacksmithing or enchanting system could be part of one plugin.

This is part of a list of ideas for plugins we'd like to start work on eventually. Reply here if you wish to help out. Feel free to chat about these on the Discord as well.

**Comment by Naatchi** [comment]
I can work on this! [https://github.com/Naatchi/Shop-System/issues](url)

**Comment by Boy0000** [comment]
Gonna be using [Shopkeeper](https://www.spigotmc.org/resources/shopkeepers.80756/) for this.
Easily updated either ingame or config. And works with looty relics etc
