### ISSUE TITLE
Mobs running away from player

### ISSUE THREAD

**Issue by Xestri** [MineInAbyss/Issue-Tracker#94]
### Expected behavior

I was expecting the mob to target the player and therefore turn back around to face the player and run towards the player after it passed me.

### Observed/Actual behavior

The mobs continued to target the player, but instead of running towards the player, ran away from the player, as if the movement was locked on the setting it was previously on. Interestingly the orbpiercers still kept shooting even when they ran the other way, and when they reached a wall, both uibutas and orbpiercers continued running towards the wall, but faced the player.

### Steps/models to reproduce

https://user-images.githubusercontent.com/97231035/148381689-67c37aa0-42ed-4e1d-a583-ba5f51c1fe44.mp4
I was able to reproduce this by forcing the mob to go underwater for a while, by making it go below the surface level of water and then run into a wall of water by doing that my self.

### Other

Where i tested this the mobs ran from ice blocks into the water, i do not know if the same happens on blocks with more friction.

**Comment by 0ffz** [comment]
This is mostly just an inherent issue with Minecraft AI. I think it gets worse with big hitboxes and faster mobs too but the only sound solution is just writing our own ai someday.

**Comment by 0ffz** [comment]
Progress will be tracked here https://github.com/MineInAbyss/Mobzy/issues/22
